title: "ASPIRE Lab"
description: "Autonomous Systems, Perception, Intelligence, and Robotic Exploration"
url: "https://aspirelabiith.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache